spring:
  application:
    name: hr.gateway
  boot:
    admin:
      client:
        username: admintoast
        password: admintoast
      url: http://admin-server:9000/
  cloud:
    nacos:
      config:
        server-addr: nacos-server:8848
        namespace: ae43ba52-fb59-4bb3-9d8f-af33f0825d0f
        group: HR_GROUP
        username: nacos
        password: ea86nazjU;
        file-extension: yml
      discovery:
        ip: 192.168.0.103
        server-addr: nacos-server:8848
        namespace: ae43ba52-fb59-4bb3-9d8f-af33f0825d0f
        group: HR_GROUP
        username: nacos
        password: ea86nazjU;
    gateway:
      metrics:
        enabled: true # 启动服务监控
      discovery:
        locator:
          enabled: false # 取消默认路径配置，
    sentinel: # Sentinel配置
      transport: # 通讯配置
        port: 8719 # Sentinel通讯端口
        dashboard: sentinel-server:8888 # Sentinel控制面板
server:
  port: 9501
management:
  server:
    port: 9591 # Actuator端口
  endpoints:
    web:
      exposure:
        include: "*" # 开启全部的监控终端
      base-path: /actuator  # 访问子路径

gateway: # 自定义的配置项
  config:
    jwt:
      header-name: token # 头信息的参数名称
      skip-auth-urls: # 跳过的检查路径
        - /actuator/
        - /system/provider/access/token

toast:
  security:
    config:
      jwt:
        sign: toast
        issuer: toast_bread
        secret: Dont_eat_on_toast
        expire: 864000 # 单位：秒；100天
      password:
        encrypt:
          repeat: 5
          salt: toast_bread