server:
  port: 9000
spring:
  security:
    user:
      name: admintoast
      password: admintoast
  application:
    name: spring.cloud.admin

toast:
  security:
    config:
      jwt:
        sign: toast
        issuer: toast_bread
        secret: Dont_eat_on_toast
        expire: 864000 # 单位：秒；100天
      password:
        encrypt:
          repeat: 5
          salt: toast_bread

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*" # 开启全部的监控终端
  endpoint:
    health:
      show-details: always